# Generated by Django 5.0.14 on 2025-12-08 22:48

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member_key_numeric",
                    models.IntegerField(
                        help_text="Unique numeric identifier for the member",
                        unique=True,
                    ),
                ),
                ("office_key_numeric", models.IntegerField(blank=True, null=True)),
                (
                    "member_aor_key",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "member_aor",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Association of Realtors",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "member_first_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "member_middle_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "member_last_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "member_full_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "member_address1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "member_address2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "member_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("member_key", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "member_mls_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "member_mobile_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "member_national_association_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "member_office_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "member_postal_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "member_preferred_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "member_state_license",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("office_key", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "office_mls_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "office_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "originating_system_member_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "originating_system_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("member_mls_access_yn", models.BooleanField(blank=True, null=True)),
                (
                    "modification_timestamp",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "original_entry_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "member_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "member_county_or_parish",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "member_state_license_state",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "member_state_or_province",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "member_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("member_type", models.CharField(blank=True, max_length=50, null=True)),
                ("member_designation", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
                "ordering": ["member_full_name"],
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("members", "Members"),
                            ("properties", "Properties"),
                            ("full", "Full Sync"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("records_processed", models.IntegerField(default=0)),
                ("records_created", models.IntegerField(default=0)),
                ("records_updated", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "last_modification_timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last modification timestamp from MLS data for incremental sync",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Log",
                "verbose_name_plural": "Sync Logs",
                "ordering": ["-started_at"],
                "get_latest_by": "started_at",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "listing_key_numeric",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("association_fee", models.FloatField(blank=True, null=True)),
                ("rooms_total", models.IntegerField(blank=True, null=True)),
                ("stories", models.IntegerField(blank=True, null=True)),
                ("bathrooms_full", models.IntegerField(blank=True, null=True)),
                ("bathrooms_half", models.IntegerField(blank=True, null=True)),
                ("bathrooms_three_quarter", models.IntegerField(blank=True, null=True)),
                ("bathrooms_partial", models.IntegerField(blank=True, null=True)),
                ("bathrooms_total_integer", models.IntegerField(blank=True, null=True)),
                ("bedrooms_total", models.IntegerField(blank=True, null=True)),
                (
                    "buyer_agent_key_numeric",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "buyer_office_key_numeric",
                    models.IntegerField(blank=True, null=True),
                ),
                ("carport_spaces", models.IntegerField(blank=True, null=True)),
                ("covered_spaces", models.FloatField(blank=True, null=True)),
                (
                    "close_price",
                    models.FloatField(blank=True, db_index=True, null=True),
                ),
                (
                    "co_list_agent_key_numeric",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "co_list_office_key_numeric",
                    models.IntegerField(blank=True, null=True),
                ),
                ("concessions_amount", models.FloatField(blank=True, null=True)),
                (
                    "cumulative_days_on_market",
                    models.IntegerField(blank=True, null=True),
                ),
                ("days_on_market", models.IntegerField(blank=True, null=True)),
                ("fireplaces_total", models.IntegerField(blank=True, null=True)),
                ("garage_spaces", models.FloatField(blank=True, null=True)),
                (
                    "list_agent_key_numeric",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("list_office_key_numeric", models.IntegerField(blank=True, null=True)),
                ("list_price", models.FloatField(blank=True, null=True)),
                ("lease_amount", models.FloatField(blank=True, null=True)),
                ("living_area", models.FloatField(blank=True, null=True)),
                ("building_area_total", models.FloatField(blank=True, null=True)),
                ("lot_size_acres", models.FloatField(blank=True, null=True)),
                ("lot_size_square_feet", models.FloatField(blank=True, null=True)),
                ("number_of_buildings", models.IntegerField(blank=True, null=True)),
                ("number_of_units_leased", models.IntegerField(blank=True, null=True)),
                ("number_of_units_total", models.IntegerField(blank=True, null=True)),
                ("lot_size_area", models.FloatField(blank=True, null=True)),
                ("main_level_bedrooms", models.IntegerField(blank=True, null=True)),
                ("original_list_price", models.FloatField(blank=True, null=True)),
                ("parking_total", models.FloatField(blank=True, null=True)),
                ("open_parking_spaces", models.IntegerField(blank=True, null=True)),
                ("photos_count", models.IntegerField(blank=True, null=True)),
                ("street_number_numeric", models.IntegerField(blank=True, null=True)),
                ("tax_annual_amount", models.FloatField(blank=True, null=True)),
                ("year_built", models.IntegerField(blank=True, null=True)),
                ("year_built_effective", models.IntegerField(blank=True, null=True)),
                ("mobile_length", models.IntegerField(blank=True, null=True)),
                ("mobile_width", models.IntegerField(blank=True, null=True)),
                ("bathrooms_one_quarter", models.IntegerField(blank=True, null=True)),
                ("cap_rate", models.FloatField(blank=True, null=True)),
                ("number_of_pads", models.IntegerField(blank=True, null=True)),
                ("stories_total", models.IntegerField(blank=True, null=True)),
                ("year_established", models.IntegerField(blank=True, null=True)),
                (
                    "association_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "association_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "buyer_agent_fax",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "buyer_agent_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "buyer_agent_full_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "buyer_agent_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "buyer_agent_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "buyer_agent_middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "buyer_agent_mls_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "buyer_agent_office_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "buyer_agent_preferred_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "buyer_agent_state_license",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("buyer_agent_url", models.URLField(blank=True, null=True)),
                (
                    "buyer_office_fax",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "buyer_office_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "buyer_office_mls_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "buyer_office_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "buyer_office_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("buyer_office_url", models.URLField(blank=True, null=True)),
                (
                    "co_list_agent_fax",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "co_list_agent_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "co_list_agent_full_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "co_list_agent_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "co_list_agent_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "co_list_agent_middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "co_list_agent_mls_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "co_list_agent_office_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "co_list_agent_preferred_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "co_list_agent_state_license",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("co_list_agent_url", models.URLField(blank=True, null=True)),
                (
                    "co_list_office_fax",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "co_list_office_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "co_list_office_mls_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "co_list_office_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "co_list_office_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("co_list_office_url", models.URLField(blank=True, null=True)),
                ("copyright_notice", models.TextField(blank=True, null=True)),
                (
                    "cross_street",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("directions", models.TextField(blank=True, null=True)),
                ("disclaimer", models.TextField(blank=True, null=True)),
                ("exclusions", models.TextField(blank=True, null=True)),
                (
                    "frontage_length",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("inclusions", models.TextField(blank=True, null=True)),
                (
                    "list_agent_fax",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "list_agent_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "list_agent_full_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "list_agent_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "list_agent_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "list_agent_middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "list_agent_mls_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "list_agent_office_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "list_agent_preferred_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "list_agent_state_license",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("list_agent_url", models.URLField(blank=True, null=True)),
                (
                    "list_office_fax",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "list_office_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "list_office_mls_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "list_office_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "list_office_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("list_office_url", models.URLField(blank=True, null=True)),
                ("listing_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "listing_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "originating_system_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "originating_system_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "originating_system_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "other_parking",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ownership", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "parcel_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("postal_code", models.CharField(blank=True, max_length=10, null=True)),
                ("public_remarks", models.TextField(blank=True, null=True)),
                (
                    "rv_parking_dimensions",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "showing_contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "showing_contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "source_system_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "source_system_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "source_system_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "street_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "street_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "subdivision_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("unit_number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "unparsed_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("virtual_tour_url_branded", models.URLField(blank=True, null=True)),
                ("virtual_tour_url_unbranded", models.URLField(blank=True, null=True)),
                ("zoning", models.CharField(blank=True, max_length=100, null=True)),
                ("zoning_description", models.TextField(blank=True, null=True)),
                (
                    "lot_size_dimensions",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("topography", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "builder_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "buyer_team_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "co_buyer_agent_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "co_buyer_agent_full_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "co_buyer_agent_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "co_buyer_agent_state_license",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "co_buyer_office_mls_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "co_buyer_office_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("doh1", models.CharField(blank=True, max_length=100, null=True)),
                ("doh2", models.CharField(blank=True, max_length=100, null=True)),
                ("doh3", models.CharField(blank=True, max_length=100, null=True)),
                ("license1", models.CharField(blank=True, max_length=100, null=True)),
                ("license2", models.CharField(blank=True, max_length=100, null=True)),
                ("license3", models.CharField(blank=True, max_length=100, null=True)),
                ("make", models.CharField(blank=True, max_length=100, null=True)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("park_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "postal_code_plus4",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("serial_u", models.CharField(blank=True, max_length=100, null=True)),
                ("serial_x", models.CharField(blank=True, max_length=100, null=True)),
                ("serial_xx", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "street_additional_info",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "street_suffix_modifier",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "water_body_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("association_yn", models.BooleanField(blank=True, null=True)),
                ("attached_garage_yn", models.BooleanField(blank=True, null=True)),
                ("carport_yn", models.BooleanField(blank=True, null=True)),
                ("cooling_yn", models.BooleanField(blank=True, null=True)),
                ("fireplace_yn", models.BooleanField(blank=True, null=True)),
                ("garage_yn", models.BooleanField(blank=True, null=True)),
                ("heating_yn", models.BooleanField(blank=True, null=True)),
                ("home_warranty_yn", models.BooleanField(blank=True, null=True)),
                ("horse_yn", models.BooleanField(blank=True, null=True)),
                (
                    "internet_address_display_yn",
                    models.BooleanField(blank=True, null=True),
                ),
                ("searchable_yn", models.BooleanField(blank=True, null=True)),
                (
                    "internet_entire_listing_display_yn",
                    models.BooleanField(blank=True, null=True),
                ),
                ("open_parking_yn", models.BooleanField(blank=True, null=True)),
                ("pool_private_yn", models.BooleanField(blank=True, null=True)),
                ("senior_community_yn", models.BooleanField(blank=True, null=True)),
                ("spa_yn", models.BooleanField(blank=True, null=True)),
                ("view_yn", models.BooleanField(blank=True, null=True)),
                ("new_construction_yn", models.BooleanField(blank=True, null=True)),
                (
                    "internet_automated_valuation_display_yn",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "internet_consumer_comment_yn",
                    models.BooleanField(blank=True, null=True),
                ),
                ("lease_considered_yn", models.BooleanField(blank=True, null=True)),
                ("property_attached_yn", models.BooleanField(blank=True, null=True)),
                ("waterfront_yn", models.BooleanField(blank=True, null=True)),
                ("close_date", models.DateField(blank=True, db_index=True, null=True)),
                ("contingent_date", models.DateField(blank=True, null=True)),
                (
                    "contract_status_change_date",
                    models.DateField(blank=True, null=True),
                ),
                ("listing_contract_date", models.DateField(blank=True, null=True)),
                ("off_market_date", models.DateField(blank=True, null=True)),
                ("on_market_date", models.DateField(blank=True, null=True)),
                ("purchase_contract_date", models.DateField(blank=True, null=True)),
                ("withdrawn_date", models.DateField(blank=True, null=True)),
                (
                    "modification_timestamp",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "original_entry_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "photos_change_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("price_change_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "status_change_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "association_fee_frequency",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "buyer_agent_aor",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "co_list_agent_aor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "co_list_office_aor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "concessions",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "county_or_parish",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "direction_faces",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "elementary_school",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "elementary_school_district",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "high_school",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "high_school_district",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "list_agent_aor",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "list_office_aor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "listing_service",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "living_area_units",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "lot_size_units",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mls_area_major",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "middle_or_junior_school",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "middle_or_junior_school_district",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("mls_status", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "occupant_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "postal_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "property_sub_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "property_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "standard_status",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "state_or_province",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "street_dir_prefix",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "street_dir_suffix",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "street_suffix",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("lease_term", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "living_area_source",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "year_built_source",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("accessibility_features", models.TextField(blank=True, null=True)),
                ("appliances", models.TextField(blank=True, null=True)),
                ("architectural_style", models.TextField(blank=True, null=True)),
                ("association_amenities", models.TextField(blank=True, null=True)),
                ("association_fee_includes", models.TextField(blank=True, null=True)),
                ("basement", models.TextField(blank=True, null=True)),
                ("buyer_agent_designation", models.TextField(blank=True, null=True)),
                ("co_list_agent_designation", models.TextField(blank=True, null=True)),
                ("construction_materials", models.TextField(blank=True, null=True)),
                ("cooling", models.TextField(blank=True, null=True)),
                ("door_features", models.TextField(blank=True, null=True)),
                ("exterior_features", models.TextField(blank=True, null=True)),
                ("flooring", models.TextField(blank=True, null=True)),
                (
                    "green_building_verification_type",
                    models.TextField(blank=True, null=True),
                ),
                ("heating", models.TextField(blank=True, null=True)),
                ("interior_features", models.TextField(blank=True, null=True)),
                ("laundry_features", models.TextField(blank=True, null=True)),
                ("list_agent_designation", models.TextField(blank=True, null=True)),
                ("listing_terms", models.TextField(blank=True, null=True)),
                ("lot_features", models.TextField(blank=True, null=True)),
                ("other_equipment", models.TextField(blank=True, null=True)),
                ("parking_features", models.TextField(blank=True, null=True)),
                ("patio_and_porch_features", models.TextField(blank=True, null=True)),
                ("pool_features", models.TextField(blank=True, null=True)),
                ("property_condition", models.TextField(blank=True, null=True)),
                ("roof", models.TextField(blank=True, null=True)),
                ("security_features", models.TextField(blank=True, null=True)),
                ("sewer", models.TextField(blank=True, null=True)),
                (
                    "showing_contact_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("utilities", models.TextField(blank=True, null=True)),
                ("vegetation", models.TextField(blank=True, null=True)),
                ("view", models.TextField(blank=True, null=True)),
                ("water_source", models.TextField(blank=True, null=True)),
                ("window_features", models.TextField(blank=True, null=True)),
                ("current_use", models.TextField(blank=True, null=True)),
                ("fencing", models.TextField(blank=True, null=True)),
                ("fireplace_features", models.TextField(blank=True, null=True)),
                ("green_energy_generation", models.TextField(blank=True, null=True)),
                ("body_type", models.CharField(blank=True, max_length=100, null=True)),
                ("building_features", models.TextField(blank=True, null=True)),
                (
                    "business_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("common_walls", models.TextField(blank=True, null=True)),
                ("community_features", models.TextField(blank=True, null=True)),
                ("electric", models.TextField(blank=True, null=True)),
                ("foundation_details", models.TextField(blank=True, null=True)),
                ("green_energy_efficient", models.TextField(blank=True, null=True)),
                ("green_indoor_air_quality", models.TextField(blank=True, null=True)),
                ("green_location", models.TextField(blank=True, null=True)),
                ("green_sustainability", models.TextField(blank=True, null=True)),
                ("green_water_conservation", models.TextField(blank=True, null=True)),
                ("levels", models.TextField(blank=True, null=True)),
                ("other_structures", models.TextField(blank=True, null=True)),
                ("possible_use", models.TextField(blank=True, null=True)),
                ("rent_includes", models.TextField(blank=True, null=True)),
                ("road_frontage_type", models.TextField(blank=True, null=True)),
                ("road_surface_type", models.TextField(blank=True, null=True)),
                ("room_type", models.TextField(blank=True, null=True)),
                ("skirt", models.CharField(blank=True, max_length=100, null=True)),
                ("spa_features", models.TextField(blank=True, null=True)),
                ("special_listing_conditions", models.TextField(blank=True, null=True)),
                (
                    "structure_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "unit_type_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("waterfront_features", models.TextField(blank=True, null=True)),
                (
                    "geo_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("basement_finished", models.IntegerField(blank=True, null=True)),
                (
                    "const_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "power_production_solar_year_install",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "solar_finance_company",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "solar_leasing_company",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "solar_ownership",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "power_production_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("level_data", models.TextField(blank=True, null=True)),
                ("above_grade_finished_area", models.FloatField(blank=True, null=True)),
                (
                    "buyer_financing",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "master_bedroom_level",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "irrigation_water_rights_acres",
                    models.IntegerField(blank=True, null=True),
                ),
                ("cancellation_date", models.DateField(blank=True, null=True)),
                (
                    "image_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "co_buyer_agent_key_numeric",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "co_buyer_agent_fax",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "co_buyer_agent_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "co_buyer_agent_middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "co_buyer_agent_mls_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "co_buyer_agent_preferred_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("co_buyer_agent_url", models.URLField(blank=True, null=True)),
                (
                    "co_buyer_agent_aor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("co_buyer_agent_designation", models.TextField(blank=True, null=True)),
                (
                    "co_buyer_office_key_numeric",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "co_buyer_office_fax",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "co_buyer_office_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "co_buyer_office_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("co_buyer_office_url", models.URLField(blank=True, null=True)),
                ("idx_contact_information", models.TextField(blank=True, null=True)),
                ("vow_contact_information", models.TextField(blank=True, null=True)),
                ("short_term_rental_yn", models.BooleanField(blank=True, null=True)),
                ("adu_yn", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
                "unique_together": {
                    (
                        "listing_key_numeric",
                        "buyer_agent_key_numeric",
                        "list_agent_key_numeric",
                        "standard_status",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="AgentStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(db_index=True)),
                (
                    "aor",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Association of Realtors for this stat",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "total_volume",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                    ),
                ),
                (
                    "listing_volume",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "buyer_volume",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("transaction_count", models.IntegerField(default=0)),
                ("listing_count", models.IntegerField(default=0)),
                ("buyer_count", models.IntegerField(default=0)),
                (
                    "rank_overall",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "rank_in_aor",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "average_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="sales.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Stats",
                "verbose_name_plural": "Agent Stats",
                "ordering": ["-total_volume"],
                "unique_together": {("member", "year", "aor")},
            },
        ),
    ]
